spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  flyway:
    enabled: false
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  secret: QhwrE4l/ZAPoOUku3nLOstJAjcQ5AbRYyJSZ2O9k/z4=